name: Jira Issues

on:
  issues:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Jira Login
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - name: Jira Create issue
      uses: atlassian/gajira-create@v2.0.0
      with:
        # Key of the project
        project: DS 
        # Type of the issue to be created. Example: 'Incident'
        issuetype: Task
        # Issue summary
        summary: "${{ github.repository}} Issue #${{ github.event.issue.number}} ${{ github.event.issue.title}}"
        # Issue description
        description: ${{ github.event.issue.body}} ${{ github.event.issue.html_url}}
